# Generated by Django 4.2.1 on 2023-06-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='list',
            name='sort_criterion',
            field=models.CharField(choices=[('PR', 'By Priority'), ('ED', 'By End Date')], default='ED', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
