@startuml

!startsub STYLE

skinparam dpi 200
skinparam style strictuml
skinparam ParticipantPadding 100

hide footbox

autoactivate on

!endsub

!startsub PARTICIPANTS

actor 사용자
boundary "Web Framework" as view

!endsub

@enduml