@startuml
!includesub style.puml!STYLE

mainframe **UC009** 남은 기간으로 정렬한다

actor 사용자
participant ":Task" as Task

사용자 -> Task : 정렬 버튼 클릭
Task --> 사용자 : 정렬 기준 선택 폼 제공
사용자 -> Task : 남은 기간 선택
Task -> Task : sort()
deactivate Task
deactivate Task

@enduml