@startuml
!includesub style.puml!STYLE

mainframe **UC002** 목록을 수정한다

actor 사용자
participant ":List" as List

사용자 -> List : edit()
List --> 사용자 : 입력 폼 제공

alt 입력
	사용자 -> List : 사용자가 수정사항을 입력한다
	List -> List : 목록을 수정한다
	deactivate List
	deactivate List
else 취소
	사용자 -> List : 사용자가 수정을 취소한다
end

@enduml