@startuml
!includesub style.puml!STYLE

mainframe **UC003** 목록을 삭제한다

!includesub style.puml!PARTICIPANTS
participant ":List" as List

사용자 -> view : 목록 삭제 버튼 클릭
view --> 사용자 : 삭제 여부 확인 페이지 제공

alt 확인
	사용자 -> view : 확인 버튼 클릭
	view -> List : delete()
	deactivate List
	view --> 사용자 : 삭제 알림
else 취소
	사용자 -> view : 취소 버튼 클릭
	view --> 사용자 : 삭제 취소 알림
end

@enduml