@startuml
!includesub style.puml!STYLE

mainframe **UC004** 작업을 생성한다

!includesub style.puml!PARTICIPANTS
participant ":Task" as Task

사용자 -> view : 작업 생성 버튼 클릭
view --> 사용자 : 입력 폼 제공

사용자 -> view : 정보 입력 후 확인 버튼 클릭
view -> view : 입력된 정보가 올바른지 검증
deactivate view

alt 올바름
	view -> Task : create()
	deactivate Task
	deactivate Task
	view --> 사용자 : 생성 완료 알림
else 올바르지 않음
	view -[hidden]> view 
	view --> 사용자 : 오류 메세지 출력
end

@enduml