@startuml
!includesub style.puml!STYLE

mainframe **UC007** 작업의 완료상태를 변경한다

!includesub style.puml!PARTICIPANTS
participant ":Task" as Task

사용자 -> view : 완료상태 변경 버튼 클릭
view -> Task : toggle_done()

@enduml