@startuml
!includesub style.puml!STYLE

mainframe **UC005** 작업을 수정한다

!includesub style.puml!PARTICIPANTS
participant ":Task" as Task

사용자 -> view : 작업 수정 버튼 클릭
view --> 사용자 : 입력 폼 제공

alt 입력
	사용자 -> view : 수정내용 입력 후 확인 버튼 클릭
	view -> Task : edit()
	deactivate Task
	deactivate view
else 취소
	사용자 -> view : 취소 버튼 클릭
end

@enduml