@startuml
!includesub style.puml!STYLE

mainframe **UC006** 작업을 삭제한다

actor 사용자
participant ":Task" as Task

사용자 -> Task :작업 삭제 버튼 클릭
Task --> 사용자 : 삭제 여부 확인 페이지 제공

alt 확인
	사용자 -> Task : 확인 버튼 클릭
	Task -> Task : delete()
	deactivate Task
	Task --> 사용자 : 삭제 알림
else 취소
	사용자 -> Task : 취소 버튼 클릭
	Task --> 사용자 : 삭제 취소 알림
end

@enduml