@startuml
!includesub style.puml!STYLE

mainframe **UC001** 목록을 생성한다

!includesub style.puml!PARTICIPANTS
participant ":List" as List

사용자 -> view : 목록 생성 버튼 클릭
view --> 사용자 : 입력 폼 제공

alt 생성
	사용자 -> view: 입력 후 확인버튼 클릭
	view -> List : create()
	deactivate List
	deactivate view
else 취소
	사용자 -> view : 취소 버튼 클릭

end

@enduml