@startuml
!includesub style.puml!STYLE

mainframe **UC008** 작업을 정렬한다

!includesub style.puml!PARTICIPANTS
participant ":Task" as Task

사용자 -> view : 정렬 버튼 클릭
view --> 사용자 : 정렬 기준 선택 폼 제공
사용자 -> view : 정렬 기준 선택
view -> Task : sort()
deactivate Task
deactivate view

@enduml