@startuml
!includesub style.puml!STYLE

mainframe **UC013** 계정을 등록한다

actor 사용자
participant ":User" as User

사용자 -> User : signup()

loop WHILE 입력이 올바를때까지
	User --> 사용자 : 입력 폼 전송
	사용자 -> User : 입력
end

User --> 사용자 : 계정을 제공한다

@enduml