@startuml
!includesub style.puml!STYLE

mainframe **UC011** 작업을 미리 알려준다

!includesub style.puml!PARTICIPANTS
participant ":Task" as Task

view -> Task : is_done()
Task --> view : True/False

opt True
	view --> 사용자 : 작업 알림
end

@enduml