@startuml
!includesub style.puml!STYLE

mainframe **UC013** 계정을 등록한다

!includesub style.puml!PARTICIPANTS
participant ":User" as User

사용자 -> view : 계정등록 버튼 클릭

loop WHILE 입력이 올바를때까지
	view --> 사용자 : 입력 폼 전송
	사용자 -> view : 입력 후 확인 버튼 클릭
end

view -> User : signup()

@enduml