@startuml
!includesub style.puml!STYLE

mainframe **UC013** 계정을 등록한다

actor 사용자
participant ":User" as User

사용자 -> User : 계정등록 버튼 클릭

loop WHILE 입력이 올바를때까지
	User --> 사용자 : 입력 폼 전송
	사용자 -> User : 입력 후 확인 버튼 클릭
end

User -> User : signup()

@enduml