@startuml
!includesub style.puml!STYLE

mainframe **UC014** 로그인한다

actor 사용자
participant ":User" as User

사용자 -> User : 로그인 버튼 클릭
User --> 사용자 : 입력 폼 전송

사용자 -> User : 입력 후 확인 버튼 클릭
alt 올바른 입력
	User -> User : login()
	deactivate User
	User --> 사용자 : 로그인 확인 메세지 출력
else
	사용자 -[hidden]> User
	User --> 사용자 : 오류 메세지 출력
end


@enduml