@startuml
!includesub style.puml!STYLE

mainframe **UC012** 완료된 작업의 보기옵션을 변경시킨다

!includesub style.puml!PARTICIPANTS
participant ":FrontendOptions" as FO

사용자 -> view : 보기옵션 변경버튼 클릭
view -> FO : hide_finished_tasks 토글

@enduml